# Generated by Django 4.2.7 on 2023-12-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_created_at_student_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='students',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='students',
        ),
        migrations.RemoveField(
            model_name='test',
            name='students',
        ),
        migrations.AddField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(to='api.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(to='api.student'),
        ),
        migrations.AddField(
            model_name='test',
            name='students',
            field=models.ManyToManyField(to='api.student'),
        ),
    ]
