# Generated by Django 4.2.7 on 2023-12-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assessment_exam_score_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='students',
        ),
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
