# Generated by Django 4.2.7 on 2023-12-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_assessment_students_assessment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='students',
        ),
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
