# Generated by Django 4.2.7 on 2023-12-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_exam_students_exam_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('class_num', 'code')},
        ),
    ]
