# Generated by Django 4.2.7 on 2023-12-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('student', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('student', 'code')},
        ),
    ]
