# Generated by Django 4.2.7 on 2023-12-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_assessment_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='class_num',
            new_name='class_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='matric_num',
            new_name='matric_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('class_number', 'code')},
        ),
    ]
