# Generated by Django 4.2.7 on 2023-12-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_class_num_attendance_class_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_number',
            field=models.IntegerField(),
        ),
    ]
