# Generated by Django 4.2.7 on 2023-12-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_attendance_class_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='code',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='code',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='code',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('class_number', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('student', 'course')},
        ),
    ]
