# Generated by Django 4.2.7 on 2023-12-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_assessment_course_alter_attendance_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Male', max_length=11),
        ),
    ]
